---
title: Bedraad meerdere knoppen
hero_image: images/banner.png
description: Hoe meerdere drukknoppen op een Raspberry Pi Pico aan te sluiten
version: 4
listed: false
copyedit: false
last_tested: "2022-02-10"
steps:
  - title: Bedraad meerdere knoppen
