title: Wire multiple buttons
hero_image: images/banner.png
description: How to attach multiple push buttons to a Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-10"
steps:
  - 
    title: Wire multiple buttons
