---
title: Câbler plusieurs boutons
hero_image: images/banner.png
description: Comment relier plusieurs boutons-poussoirs à un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-10"
steps:
  - title: Câbler plusieurs boutons
